---
kind: Service
apiVersion: v1
metadata:
  name: {{.Values.srvname.be}}
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: myapp
    tier: backend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80